config/routes.rb
ThaaliyolaRor::Application.routes.draw do
  resources :reservations

  get "reports/index"
    resources :issuings

    resources :languages

    resources :languagedivisions

    resources :users

    resources :shelves

    resources :categories

    resources :shelfpositions

    resources :categorizations

    resources :authorships

    resources :authors

    resources :books

    get "list/index"
    get "books/index"
    get "reports/index"
    get "reports" => "reports#index"
    post "reports/showreport" => "reports#showreport"
    post "sign_in" => "users#sign_in"
    get "sign_in" => "users#login"
    get "success" => "users#success"
    get "sign_up" => "users#new"
    post "logout" => "users#sign_out"
    post "users/:id/reset_password" => "users#reset_password"
    get "users/:id/reset_password" => "users#password_reset", as:"password_reset"
    get "edit_user_photo" => "users#changephoto"
    patch "users/:id/issue" => "users#issue", as:"issue"
    patch "users/:id/renew" => "users#renew", as:"renew"
    patch "users/:id/return" => "users#return", as:"return"
    patch "users/:id/reset_password" => "users#reset_password"
    root :to => "books#index"

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :issuings
    has_many :books, through: :issuings
    accepts_nested_attributes_for :books
    validates :username, uniqueness: true
    validates_confirmation_of :password, :message => "Passwords must match"
    validates_presence_of :password_confirmation, :if => :password_changed?
    has_attached_file :profpic
 validates_attachment_content_type :profpic, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
#    before_save :encrypt_password
    #def encrypt_password
        #puts "Current Password" + self.password
        #self.password = Digest::SHA1.hexdigest(self.password)
    #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, :with => :not_found
    def not_found
        render :template=>"/error/404_user.html.erb", :status=>404
    end

   include ApplicationHelper
    before_action :set_user, only: [:show, :edit, :update, :destroy,:password_reset, :reset_password, :issue, :return, :renew]

    helper_method :isadmin
    helper_method :current_user
    # GET /users
    # GET /users.json
    def index
        @current_user=session[:user]
        if not @current_user.nil?
            if User.where('username = ?',@current_user).first.admin==true
                @users = User.all
            end
        end
    end

    def reset_password
        @oldpassword=params[:user][:currentpassword]
        @old_sha = Digest::SHA1.hexdigest(@oldpassword)
        if @old_sha!=@user.password
            @user.errors[:base] << "Current Password Incorrect"
            render "password_reset"

      else
            @newpassword = params[:user][:newpassword]
            @newpassword_confirmation = params[:user][:newpassword_confirmation]
            if @newpassword!=@newpassword_confirmation
                @user.errors[:base] << "Passwords Donot Match"
                render 'password_reset'
            else            
                if @user.update_attribute(:password, Digest::SHA1.hexdigest(params[:user][:newpassword]))
                    notice="Password Updated"
                    signinnotice(notice)
                    redirect_to @user, notice:notice
                end
            end
        end
     end

    def sign_up
        @users = User.all
    end

    def sign_out
        session.delete(:user)
        notice="Logged Out Succesfully"
        signinnotice(notice)
        @currenturl=request.referrer
        respond_to do |format|
            format.html { redirect_to @currenturl,notice:notice}
        end
    end

    def success
    end

    def renew
        begin
            @book = Book.find(params[:user][:book][:id])
            if @user.books.where(:id=>@book.id).empty?
                notice="Book not issued to user"
                redirect_to @user, notice:notice
            else
                @returndate = Issuing.where(:book=>@book).first.dateofreturn
                @newreturndate = @returndate+14;
                if not Issuing.where(:book=>@book).first.renewed == true
                    Issuing.where(:book=>@book).first.update(:dateofreturn=>@newreturndate,:renewed=>true)
                    notice="Book Renewed"
                else
                    notice="Book already renewed"
                end
                redirect_to @user, notice:notice
            end
        rescue 
            notice="Book Not Found"
            redirect_to @user, notice:notice
        end
    end

    def issue
        begin
        @book = Book.find(params[:user][:book][:id])
        if not @user.books.where(:id=>@book.id).empty?
            notice="Book already issued"
                redirect_to @user, notice:notice
            else
                Issuing.create(:book=>@book, :user=>@user, :dateofissue=>DateTime.now(), :dateofreturn=>14.days.from_now) 
                respond_to do |format|
                    notice="Book Issued"
                    format.html { redirect_to @user,notice:notice}
                end
            end
        rescue 
            notice="Book Not Found"
            redirect_to @user, notice:notice
        end
           end

    def return
        begin
            @book = Book.find(params[:user][:book][:id])
            if @user.books.where(:id=>@book.id).empty?
                notice="Book not issued to user"
                redirect_to @user, notice:notice
            else
               @issuing = Issuing.where(:book_id=>@book.id, :user_id=>@user.id).first
                @issuing.delete
                respond_to do |format|
                    notice="Book Returned"
                    format.html { redirect_to @user,notice:notice}
                end
            end
       rescue
            notice="Book Not Found"
            redirect_to @user, notice:notice
        end
    end


    def login
    end
    def sign_in
        @username=params[:user][:username]
        @password=params[:user][:password]
        @sha_password = Digest::SHA1.hexdigest(@password)
        @currenturl=request.referrer
        @user=User.where('username LIKE ?',@username)
        if @user.empty?
            notice="Incorrect Username"
        else
            @pword=@user.first.password
            if @pword==@sha_password
                notice="Login Successful"
                session[:user]=@username
            else
                notice="Incorrect password"
            end
        end
        signinnotice(notice)
        respond_to do |format|
            format.html { redirect_to @currenturl,notice:notice }
            format.json { render action: 'show', status: :created, location: sign_in_path }
        end
    end

    # GET /users/1
    # GET /users/1.json
    def show
    end

    # GET /users/new
    def new
        @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users
    # POST /users.json
    def create
        username=params[:user][:username]
        password=params[:user][:password]
        password_confirmation=params[:user][:password_confirmation]
        @sha_password = Digest::SHA1.hexdigest(password)
        @sha_password_confirmation = Digest::SHA1.hexdigest(password_confirmation)
        @parameters=user_params
        @parameters[:password]=@sha_password
        @parameters[:password_confirmation]=@sha_password_confirmation
        @user = User.new(@parameters)
            notice="User Succesfully Created"
            signinnotice(notice)
            if @user.save
puts "Errors = "
puts @user.errors.full_messages

                if not session[:user] or not User.where("username = ?",session[:user]).first.admin?
                session[:user]=username
                end
                puts "Session" + session[:user]
                redirect_to @user
            else
                respond_to do |format|
                format.html{render action: 'new'}
                format.html{render json: @user.errors, status: :unprocessable_entity }
                end
            end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
                respond_to do |format|
            if @user.update(user_params)
         notice="Details Saved"
        signinnotice(notice)
       format.html { redirect_to @user, notice:notice }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
        @user.destroy
        session.delete(:user)
        respond_to do |format|
            format.html { redirect_to root_path }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :librarian, :admin, :address, :email, :phone, :name, :currentpassword, :newpassword, :newpassword_confirmation, :book, :profpic, :locale)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_formbookaction.haml
= form_for(@user) do |f|
  .input-group
    = f.fields_for :book do |book_form|
      = book_form.text_field :id, class:"form-control", placeholder:"Book Serial Number"
    .input-group-btn
      %button.btn.btn-danger.dropdown-toggle{type:"button",data:{toggle:"dropdown"}}
        Action
        %span.caret
      %ul.dropdown-menu.dropdown-menu-right{role:"menu"}
        %li
          %a{href:"",onclick:"issue_book()"}
            Issue
        %li
          %a{href:"",onclick:"return_book()"}
            Return
        %li
          %a{href:"",onclick:"renew_book()"}
            Renew
:javascript
  function return_book()
  {
    $('#edit_user_#{@user.id}').attr('action',"#{return_path(@user)}");
    $('.edit_user').submit();
  }
  function renew_book()
  {
    $('#edit_user_#{@user.id}').attr('action',"#{renew_path(@user)}");
    $('.edit_user').submit();
  }
  function issue_book()
  {
    $('#edit_user_#{@user.id}').attr('action',"#{issue_path(@user)}");
    $('.edit_user').submit();
  }

app/views/users/_formcreate.haml
= form_for(@user, class:"form-signin") do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count,"error")
        prohibited this user from being saved
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  %ul.nav.nav-tabs#tabs{data:{tabs:"tabs"}}
    %li
      %a.active{href:"#logindetails",data:{toggle:"tab"},style:"background:grey;color:black;margin-right:1%;padding-right:1%"} Login Details
    %li
      %a{href:"#userdetails",style:"background:grey;color:black",data:{toggle:"tab"}} User Details

  #my-tab-content.tab-content
    .tab-pane.active#logindetails{style:"padding-left:2%;padding-right:2%"}
      = f.text_field :username, class: "form-control", placeholder: "Username"
      = f.password_field :password, class: "form-control", placeholder: "Password"
      = f.password_field :password_confirmation, class: "form-control", placeholder: "Repeat Password"

    .tab-pane#userdetails{style: "padding-left:2%;padding-right:2%"}
      = f.text_field :name, class: "form-control", placeholder: "Name", required: "true"
      = f.text_area :address, class: "form-control", placeholder: "Address", required: "true"
      = f.email_field :email, class: "form-control", placeholder: "EMail"
      = f.text_field :phone, class: "form-control", placeholder: "Phone"
      = f.select :locale, options_for_select(LANGUAGES, I18n.locale.to_s),{}, style: "width:100%"
      = f.file_field :profpic, class: "btn", title: "Choose Profile Pic"
      = button_tag 'Sign Up', class: "btn btn-normal", style: "width: 100%;color:black"

:javascript
  $(document).ready(function() { $("#user_locale").select2({placeholder: "Language", allowClear: true});});

:css
  .form-control
  {
    margin-top: 1%;
    margin-bottom:1%;
  }

app/views/users/_formedit.haml
= form_for(@user, class:"form-signin") do |f|
  = f.text_field :name, class: "form-control", placeholder: "Name", required: "true"
  = f.text_area :address, class: "form-control", placeholder: "Address", required: "true"
  = f.email_field :email, class: "form-control", placeholder: "EMail"
  = f.text_field :phone, class: "form-control", placeholder: "Phone"
  = f.select :locale, options_for_select(LANGUAGES, I18n.locale.to_s),{}, style: "width:100%"
  = f.file_field :profpic, class: "btn", title: "Choose Profile Pic"
  = button_tag 'Update', class: "btn btn-normal", style: "width: 100%;color:black"

:javascript
  $(document).ready(function() { $("#user_locale").select2({placeholder: "Language", allowClear: true});});

:css
  .form-control
  {
    margin-top: 1%;
    margin-bottom:1%;
  }

app/views/users/_formresetpassword.haml
= form_for(@user, url: "reset_password", class:"form-signin") do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count,"error")
        prohibited password from being changed
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  = f.password_field :currentpassword, class:"form-control", placeholder: "Current Password"
  = f.password_field :newpassword, class:"form-control", placeholder: "New Password"
  = f.password_field :newpassword_confirmation, class: "form-control"
  = button_tag "Change", class: "btn btn-normal", style:"width:100%;color:black"

app/views/users/_formsignin.haml
= form_for(@user=User.new, :url=>sign_in_path) do |f|
  = f.text_field :username,class:"form-control",placeholder:"Username"
  %br
  = f.text_field :password,type:"password",class:"form-control",placeholder:"Password"
  %br
  = button_tag "Sign In", class:"btn", style:"width:100%"

app/views/users/edit.haml
- currentuser = current_user()
- if currentuser == @user or isadmin() == true
  %h1{style:"text-align:center"} Edit #{@user.name}
  = render 'formedit'
- else
  .alert.alert-dismissable.alert-danger{style:"margin-top:2%"}
    %button.close{type:"button",data:{dismiss:"alert"},aria:{hidden:"true"}} &times;
    You Cannot Access This Page

app/views/users/index.haml
- if isadmin()
  %h1 Listing Users
  %table.table.table-hover{"width" => "100%"}
    %tr
      %th.col-md-4 Admission Number
      %th.col-md-4 Username
      %th.col-md-4 Name
    - @users.each do |user|
      %tr
        %td= link_to user.id, user
        %td= link_to user.username, user
        %td= link_to user.name, user
- else
  .alert.alert-dismissable.alert-danger(style='margin-top:2%')
    %button.close{"type" =>"button","data-dismiss" => "alert","aria-hidden" => "true"} &times;
    You cannot access this page

app/views/users/new.haml
%h1.centertext New User
= render 'formcreate'

app/views/users/reset_password.haml
- currentuser = current_user()
- if currentuser == @user or isadmin() == true
  %h1 Reset Password
  = render 'formresetpassword'
- else
  .alert.alert-dismissable.alert-danger{style:"margin-top:2%"}
    %button.close{type:"button",data:{dismiss:"alert"},aria:{hidden:"true"}} &times;
    You Cannot Access This Page

app/views/users/show.haml
- currentuser = current_user()
- if @user == currentuser or isadmin() == true
  .jumbotron{style:"margin-top:2%"}
    .row
      #left{style:"width:75%;float:left"}
        %h1= @user.name
        %br
        - @add = simple_format @user.address
        - @add = @add.gsub '<br />', '<br /><br />'
        - @add = @add.gsub '<p>', '<p style= "margin-left:1%"'
        = @user.address
        %br
        Admission Number :
        = @user.admissionnumber
        %br
        Email
        = @user.email
        %br
        Phone
        = @user.phone
      #right{style:"float:left;margin-top:5%"}
        - if @user.profpic.file?
          = image_tag @user.profpic.url, style:"width:125px;height:160px"
        - else
          = image_tag "passport_sample.png"
      - if isadmin() == true
        #left{style:"float:left;margin-top:5%"}
          = render 'formbookaction'
    .row
      = button_to "Edit Details", edit_user_path, method: "get", class: "btn btn-lg btn-primary", style: "float:left;margin-right:5%;margin-top:5%"
      = button_to "Delete User", @user, method: "delete", class: "btn btn-lg btn-danger", style: "float:left;margin-right:5%;margin-top:5%", confirm: "Are you sure to delete this account?"
      = button_to "Change Password", password_reset_path, method: "get", class: "btn btn-lg btn-primary", style: "float:left;margin-right:5%;margin-top:5%"
         
  - if not @user.books.empty?
    %table.table.table-bordered
      %tr
        %th{style:"text-align:center"}Book Serial Number
        %th{style:"text-align:center"}Book Name
        %th{style:"text-align:center"}Date of Issue
        %th{style:"text-align:center"}Date of Return
      - @user.books.each do |b|
        - @class = ""
        - @dateofissue = Date.parse(Issuing.where(book_id:b.id, user_id:@user.id).first.dateofissue.to_s)
        - @dateofreturn = Date.parse(Issuing.where(book_id:b.id, user_id:@user.id).first.dateofreturn.to_s)
        - if @dateofreturn < Date.today
          - @class = "danger"
        %tr{class: "#{@class}"}
          %td= b.id
          %td= b.name
          %td= @dateofissue.strftime("%d/%m/%Y")
          %td= @dateofreturn.strftime("%d/%m/%Y")
- else
  .alert.alert-dismissable.alert-danger{style:"margin-top:2%"}
    %button.close{type:"button",data:{dismiss:"alert"},aria:{hidden:"true"}} &times;
    You Cannot Access This Page