config/routes.rb
ThaaliyolaRor::Application.routes.draw do
  resources :reservations

  get "reports/index"
    resources :issuings

    resources :languages

    resources :languagedivisions

    resources :users

    resources :shelves

    resources :categories

    resources :shelfpositions

    resources :categorizations

    resources :authorships

    resources :authors

    resources :books

    get "list/index"
    get "books/index"
    get "reports/index"
    get "reports" => "reports#index"
    post "reports/showreport" => "reports#showreport"
    post "sign_in" => "users#sign_in"
    get "sign_in" => "users#login"
    get "success" => "users#success"
    get "sign_up" => "users#new"
    post "logout" => "users#sign_out"
    post "users/:id/reset_password" => "users#reset_password"
    get "users/:id/reset_password" => "users#password_reset", as:"password_reset"
    get "edit_user_photo" => "users#changephoto"
    patch "users/:id/issue" => "users#issue", as:"issue"
    patch "users/:id/renew" => "users#renew", as:"renew"
    patch "users/:id/return" => "users#return", as:"return"
    patch "users/:id/reset_password" => "users#reset_password"
    root :to => "books#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :authorships
    has_many :books, through: :authorships, :dependent => :destroy
    accepts_nested_attributes_for :books
    has_attached_file :photo
    validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
   
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
    belongs_to :book
    belongs_to :author
end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :authorships
    has_many :authors, through: :authorships
    accepts_nested_attributes_for :authors

    has_many :categorizations
    has_many :categories, through: :categorizations
    accepts_nested_attributes_for :categories

    has_many :issuings
    has_many :users, through: :issuings
    accepts_nested_attributes_for :users
    belongs_to :language, :dependent => :destroy

    has_many :dateofissue
    has_many :dateofreturn
    accepts_nested_attributes_for :dateofissue
    accepts_nested_attributes_for :dateofreturn
    has_attached_file :cover
    validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
    belongs_to :book
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :categorizations
    has_many :books , through: :categorizations
    accepts_nested_attributes_for :books
end

app/models/issuing.rb
class Issuing < ActiveRecord::Base
    belongs_to :book
    belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
    has_many :books
    accepts_nested_attributes_for :books
end

app/models/languagedivision.rb
class Languagedivision < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
end

app/models/shelfposition.rb
class Shelfposition < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :issuings
    has_many :books, through: :issuings
    accepts_nested_attributes_for :books
    validates :username, uniqueness: true
    validates_confirmation_of :password, :message => "Passwords must match"
    validates_presence_of :password_confirmation, :if => :password_changed?
    has_attached_file :profpic
 validates_attachment_content_type :profpic, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
#    before_save :encrypt_password
    #def encrypt_password
        #puts "Current Password" + self.password
        #self.password = Digest::SHA1.hexdigest(self.password)
    #end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  helper_method :isadmin
  helper_method :current_user

  # GET /categories
  # GET /categories.json
  def index
        if params.has_key?(:contains)
            @categories = Category.where('name LIKE ?', "%#{params[:contains]}%").paginate(page: params[:page],per_page: 10)
        else
            @categories=Category.all.paginate(page: params[:page], per_page: 10)
        end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(@categoryname)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
        def lesc(text)
            LatexToPdf.escape_latex(text)
        end    
        
        def signinnotice(str)
        if str="" 
            if notice!=""
                return notice
            else
                return ""
            end
        else
            notice=str
        end
    end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/issuings_helper.rb
module IssuingsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.haml
= form_for(@category, class:"form-signin") do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@cateory.errors.count,"error")
        prohibited this category from being saved
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :name, class:"form-control", placeholder: "Name"
  = button_tag "Update", class:"btn btn-primary", style:"width:10%"

app/views/categories/edit.haml
%h1{style:"text-align:center"}
  Edit
  = @category.name
= render 'form'

app/views/categories/index.haml
.centeredtext
  - if params.has_key?(:contains)
    %h1= t('category_under',:query => params[:contains].to_s)
  - else
    %h1= t('all_categories')
  = will_paginate @categories, renderer: BootstrapPagination::Rails
%table.table.table-hover{"width" => "100%"}
  %tr
    %th.col-md-6 Serial Number
    %th.col-md-6 Category Name
  - if params.has_key?(:page)  
    - @counter = (params[:page].to_i-1) * 10 + 1
  - else
    - @counter = 1
  - @categories.each do |category|
    %tr
      %td= @counter
      - @counter += 1
      %td= link_to category.name,category

app/views/categories/show.haml
.jumbotron{style:"margin-top:5%;padding-top:1px"}
  .row


    #left{style:"width:75%;float:left"}
      %h1= @category.name
      %p
        = @category.books.count
        Books
      %p
        - @authors=[]
        - @category.books.each do|b|
          - b.authors.each do |a|
            - @authors << a.name
        - @uniqueauth = @authors.uniq
        = @uniqueauth.length
        Authors
      - if isadmin()
        = button_to 'Edit Details', edit_category_path,{method:"get",class:"btn btn-lg btn-primary", style:"float:left;margin-right:5%;margin-top:f%"}
        = button_to 'Delete Category', @category,{method:"delete",class:"btn btn-lg btn-danger", style:"float:left;margin-right:5%;margin-top:f%", confirm:"Are you sure?"}

%table.table.table-hover{style:"width:100%"}
  %tr
    %th.col-md-6 Book
    %th.col-md-6 Author
  - @category.books.uniq_by(&:bookunique).each do |book|
    %tr
      %td= link_to book.name,book
      %td
        - book.authors.each do |auth|
          = link_to auth.name, auth